{{- if or .Values.scrape.enabled (index .Values "go-scraper" "enabled") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "reviewmaps.fullname" . }}-naver-api-creds
  labels:
    {{- include "reviewmaps.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: naver-api-creds
    creationPolicy: Owner
  data:
    - secretKey: NAVER_MAP_CLIENT_ID
      remoteRef:
        key: prod-reviewmaps-naver-api-credentials
        property: NAVER_MAP_CLIENT_ID
    - secretKey: NAVER_MAP_CLIENT_SECRET
      remoteRef:
        key: prod-reviewmaps-naver-api-credentials
        property: NAVER_MAP_CLIENT_SECRET
    - secretKey: NAVER_SEARCH_CLIENT_ID
      remoteRef:
        key: prod-reviewmaps-naver-api-credentials
        property: NAVER_SEARCH_CLIENT_ID
    - secretKey: NAVER_SEARCH_CLIENT_SECRET
      remoteRef:
        key: prod-reviewmaps-naver-api-credentials
        property: NAVER_SEARCH_CLIENT_SECRET
    - secretKey: NAVER_SEARCH_CLIENT_ID_2
      remoteRef:
        key: prod-reviewmaps-naver-api-credentials
        property: NAVER_SEARCH_CLIENT_ID_2
    - secretKey: NAVER_SEARCH_CLIENT_SECRET_2
      remoteRef:
        key: prod-reviewmaps-naver-api-credentials
        property: NAVER_SEARCH_CLIENT_SECRET_2
    - secretKey: NAVER_SEARCH_CLIENT_ID_3
      remoteRef:
        key: prod-reviewmaps-naver-api-credentials
        property: NAVER_SEARCH_CLIENT_ID_3
    - secretKey: NAVER_SEARCH_CLIENT_SECRET_3
      remoteRef:
        key: prod-reviewmaps-naver-api-credentials
        property: NAVER_SEARCH_CLIENT_SECRET_3
{{- end }}
