{{- if or .Values.server.enabled .Values.admin.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "reviewmaps.fullname" . }}-api-credentials
  labels:
    {{- include "reviewmaps.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: reviewmaps-api-credentials
    creationPolicy: Owner
  data:
    - secretKey: API_SECRET_KEY
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: API_SECRET_KEY
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: JWT_SECRET_KEY
    - secretKey: SECRET_KEY
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: SECRET_KEY
    - secretKey: KAKAO_REST_API_KEY
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: KAKAO_REST_API_KEY
    - secretKey: GOOGLE_CLIENT_ID_IOS
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: GOOGLE_CLIENT_ID_IOS
    - secretKey: GOOGLE_CLIENT_ID_ANDROID
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: GOOGLE_CLIENT_ID_ANDROID
    - secretKey: GOOGLE_PROJECT_ID
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: GOOGLE_PROJECT_ID
    - secretKey: APPLE_CLIENT_ID
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: APPLE_CLIENT_ID
    - secretKey: APPLE_TEAM_ID
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: APPLE_TEAM_ID
    - secretKey: APPLE_KEY_ID
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: APPLE_KEY_ID
    - secretKey: APPLE_PRIVATE_KEY
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: APPLE_PRIVATE_KEY
    - secretKey: FIREBASE_CREDENTIALS
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: FIREBASE_CREDENTIALS
    - secretKey: EMAIL_HOST
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: EMAIL_HOST
    - secretKey: EMAIL_PORT
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: EMAIL_PORT
    - secretKey: EMAIL_USE_TLS
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: EMAIL_USE_TLS
    - secretKey: EMAIL_HOST_USER
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: EMAIL_HOST_USER
    - secretKey: EMAIL_HOST_PASSWORD
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: EMAIL_HOST_PASSWORD
    - secretKey: DEFAULT_FROM_EMAIL
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: DEFAULT_FROM_EMAIL
{{- end }}
