{{- if or .Values.server.enabled .Values.admin.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "reviewmaps.fullname" . }}-api-credentials
  labels:
    {{- include "reviewmaps.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: reviewmaps-api-credentials
    creationPolicy: Owner
  data:
    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: DJANGO_SECRET_KEY
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: prod-reviewmaps-api-credentials
        property: JWT_SECRET_KEY
{{- end }}
