{{- if or .Values.server.enabled .Values.admin.enabled .Values.scrape.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "reviewmaps.fullname" . }}-db-credentials
  labels:
    {{- include "reviewmaps.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: reviewmaps-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_HOST
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_PORT
    - secretKey: POSTGRES_DB
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_DB
    - secretKey: POSTGRES_SERVER
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_SERVER
    - secretKey: POSTGRES_SSLMODE
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_SSLMODE
{{- end }}
