apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitapps-from-git-prod
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ggorockee/infra.git
        revision: main
        directories:
          - path: charts/helm/prod/*/*
            exclude: true
          - path: charts/helm/prod/ojeomneo/*
          - path: charts/helm/prod/reviewmaps/*

  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ggorockee/infra.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[3]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      

