apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-monitoring-prod
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/ggorockee/infra.git
      revision: main
      files:
      - path: "charts/argocd/configurations/prod/monitoring-prom-grafana-cfg.yaml"
  
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{revision}}'
        path: 'charts/helm/{{env}}/{{chartName}}'
        helm:
          valueFiles:
          - values.yaml
          - values-override.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      # Prometheus Operator가 관리하는 리소스의 status 차이 무시
      ignoreDifferences:
      - group: monitoring.coreos.com
        kind: Alertmanager
        jsonPointers:
        - /status
      - group: monitoring.coreos.com
        kind: Prometheus
        jsonPointers:
        - /status