apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps-prod
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/ggorockee/infra.git
      revision: main
      files:
      - path: "charts/argocd/configurations/prod/apps-*.yaml"
  
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{revision}}'
        path: 'charts/helm/{{env}}/{{chartName}}'
        helm:
          valueFiles:
          - '{{default "values.yaml" .valueFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true