apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-monitoring-prod
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/ggorockee/infra.git
      revision: main
      files:
      - path: "charts/argocd/configurations/prod/monitoring-prom-grafana-cfg.yaml"
  
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{revision}}'
        path: 'charts/helm/{{env}}/{{chartName}}'
        helm:
          valueFiles:
          - values.yaml
          - values-override.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
      ignoreDifferences:
      # Prometheus Operator가 관리하는 StatefulSet의 변경 무시
      - group: apps
        kind: StatefulSet
        name: prometheus-kube-prometheus-stack-prometheus
        jsonPointers:
        - /
      - group: apps
        kind: StatefulSet
        name: alertmanager-kube-prometheus-stack-alertmanager
        jsonPointers:
        - /
      # External Secrets Operator가 관리하는 ExternalSecret의 status 변경 무시
      # refreshTime, conditions 등이 주기적으로 업데이트되어 OutOfSync로 표시되는 것 방지
      - group: external-secrets.io
        kind: ExternalSecret
        jsonPointers:
        - /status