{{- if .Values.server.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ojeomneo.fullname" . }}-api-credentials
  labels:
    {{- include "ojeomneo.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: ojeomneo-api-credentials
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: JWT_SECRET_KEY
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: GEMINI_API_KEY
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: OPENAI_API_KEY
    - secretKey: OPENAI_MODEL
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: OPENAI_MODEL
    - secretKey: APPLE_PRIVATE_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: APPLE_PRIVATE_KEY
    - secretKey: APPLE_KEY_ID
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: APPLE_KEY_ID
    - secretKey: APPLE_TEAM_ID
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: APPLE_TEAM_ID
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: CLOUDFLARE_ACCOUNT_ID
    - secretKey: CLOUDFLARE_ACCOUNT_HASH
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: CLOUDFLARE_ACCOUNT_HASH
    - secretKey: CLOUDFLARE_API_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: CLOUDFLARE_API_KEY
    - secretKey: FIREBASE_ADMIN_SDK_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: FIREBASE_ADMIN_SDK_KEY
    - secretKey: KAKAO_REST_API_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: KAKAO_REST_API_KEY
    - secretKey: EMAIL_HOST
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: EMAIL_HOST
    - secretKey: EMAIL_PORT
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: EMAIL_PORT
    - secretKey: EMAIL_USE_TLS
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: EMAIL_USE_TLS
    - secretKey: EMAIL_HOST_USER
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: EMAIL_HOST_USER
    - secretKey: EMAIL_HOST_PASSWORD
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: EMAIL_HOST_PASSWORD
    - secretKey: DEFAULT_FROM_EMAIL
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: DEFAULT_FROM_EMAIL
{{- end }}
