{{- if .Values.redis.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ojeomneo.fullname" . }}-redis-credentials
  labels:
    {{- include "ojeomneo.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: ojeomneo-redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: prod-ojeomneo-redis-credentials
        property: redis-password
{{- end }}
