{{- if .Values.admin.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ojeomneo.fullname" . }}-admin-credentials
  labels:
    {{- include "ojeomneo.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: ojeomneo-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: prod-ojeomneo-admin-credentials
        property: DJANGO_SECRET_KEY
    - secretKey: DJANGO_SUPERUSER_USERNAME
      remoteRef:
        key: prod-ojeomneo-admin-credentials
        property: DJANGO_SUPERUSER_USERNAME
    - secretKey: DJANGO_SUPERUSER_EMAIL
      remoteRef:
        key: prod-ojeomneo-admin-credentials
        property: DJANGO_SUPERUSER_EMAIL
    - secretKey: DJANGO_SUPERUSER_PASSWORD
      remoteRef:
        key: prod-ojeomneo-admin-credentials
        property: DJANGO_SUPERUSER_PASSWORD
{{- end }}
