{{- if .Values.admin.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ojeomneo.fullname" . }}-admin-credentials
  labels:
    {{- include "ojeomneo.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: ojeomneo-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: prod-ojeomneo-admin-credentials
        property: DJANGO_SECRET_KEY
    - secretKey: DJANGO_ALLOWED_HOSTS
      remoteRef:
        key: prod-ojeomneo-admin-credentials
        property: DJANGO_ALLOWED_HOSTS
    - secretKey: DJANGO_CSRF_TRUSTED_ORIGINS
      remoteRef:
        key: prod-ojeomneo-admin-credentials
        property: DJANGO_CSRF_TRUSTED_ORIGINS
{{- end }}
