{{- if .Values.database.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ojeomneo.fullname" . }}-db-credentials
  labels:
    {{- include "ojeomneo.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: ojeomneo-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: prod-ojeomneo-db-credentials
        property: POSTGRES_HOST
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: prod-ojeomneo-db-credentials
        property: POSTGRES_PORT
    - secretKey: POSTGRES_USER
      remoteRef:
        key: prod-ojeomneo-db-credentials
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: prod-ojeomneo-db-credentials
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: prod-ojeomneo-db-credentials
        property: POSTGRES_DB
    - secretKey: POSTGRES_SERVER
      remoteRef:
        key: prod-ojeomneo-db-credentials
        property: POSTGRES_SERVER
{{- end }}
