{{- if .Values.server.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ojeomneo.fullname" . }}-api-credentials
  labels:
    {{- include "ojeomneo.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: ojeomneo-api-credentials
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: JWT_SECRET_KEY
    - secretKey: JWT_REFRESH_SECRET_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: JWT_REFRESH_SECRET_KEY
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: GEMINI_API_KEY
    - secretKey: APPLE_PRIVATE_KEY
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: APPLE_PRIVATE_KEY
    - secretKey: APPLE_KEY_ID
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: APPLE_KEY_ID
    - secretKey: APPLE_TEAM_ID
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: APPLE_TEAM_ID
    - secretKey: GOOGLE_APPLICATION_CREDENTIALS_JSON
      remoteRef:
        key: prod-ojeomneo-api-credentials
        property: GOOGLE_APPLICATION_CREDENTIALS_JSON
{{- end }}
