{{- range .Values.virtualServices }}
{{- if .enabled }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  hosts:
  {{- range .hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  - {{ $.Values.gateway.namespace }}/{{ $.Values.gateway.name }}
  http:
  {{- range .http }}
  - {{- if .match }}
    match:
    {{- range .match }}
    - {{- if .uri }}
      uri:
        {{- if .uri.prefix }}
        prefix: {{ .uri.prefix | quote }}
        {{- else if .uri.exact }}
        exact: {{ .uri.exact | quote }}
        {{- else if .uri.regex }}
        regex: {{ .uri.regex | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
    route:
    {{- range .route }}
    - destination:
        host: {{ .destination.host }}
        port:
          number: {{ .destination.port }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
