apiVersion: v2
appVersion: 2.4.0
description: A Library Helm Chart for grouping common logic between bitnami charts.
  This chart is not deployable by itself.
icon: https://bitnami.com/downloads/logos/bitnami-mark.png
maintainers:
- email: hello@signoz.io
  name: SigNoz
  url: https://signoz.io
name: common
sources:
- https://github.com/bitnami/charts
type: library
version: 0.0.1
