apiVersion: v2
name: istio-gateway-config
description: Istio Gateway and VirtualService unified configuration
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - istio
  - gateway
  - virtualservice
maintainers:
  - name: WoohaLabs
    email: woohaen88@gmail.com
