# Service patch to attach BackendConfig to Istio Ingress Gateway
# This patch adds the backend-config annotation
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Values.backendConfig.name }}"}'
    beta.cloud.google.com/backend-config: '{"default": "{{ .Values.backendConfig.name }}"}'
