apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $config := .Values.service.ports }}
    - port: {{ $config.port }}
      targetPort: {{ $config.targetPort }}
      protocol: {{ $config.protocol }}
      name: {{ $name }}
    {{- end }}
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}
