apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hotsao-app-secrets
  labels:
    app: hotsao
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStore | default "gcpsm-secret-store" }}
  target:
    name: {{ .Values.externalSecret.targetSecretName | default "hotsao-app-secrets" }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.secretKey | default "hotsao-app-secrets" }}
