{{- if and .Values.scraper.enabled .Values.scraper.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hotsao.fullname" . }}-scraper
  labels:
    {{- include "hotsao.labels" . | nindent 4 }}
    app.kubernetes.io/component: scraper
  {{- with .Values.scraper.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.scraper.serviceAccount.automount }}
{{- end }}
