{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.service.portName | default "http" }}
    path: /woohalabs/metrics
    interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | default "10s" }}
{{- end }}
