{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.externalSecret.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.clusterSecretStoreName }}
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "5m" }}
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
  data:
    {{- range $key, $property := .Values.externalSecret.properties }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $.Values.externalSecret.gcpSecretName }}
        property: {{ $property }}
    {{- end }}
{{- end }}
