apiVersion: v2
appVersion: 3.8.1
dependencies:
- name: common
  repository: file://charts/common
  tags:
  - bitnami-common
  version: 0.0.1
description: Bitnami Helm chart for Zookeeper
icon: https://bitnami.com/assets/stacks/zookeeper/img/zookeeper-stack-220x234.png
maintainers:
- email: hello@signoz.io
  name: SigNoz
  url: https://signoz.io
name: zookeeper
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/zookeeper
version: 0.0.1
