{{- if .Values.externalSecrets.rbac.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "argo-cd.fullname" . }}-rbac-policy
  namespace: {{ include "argo-cd.namespace" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" "rbac" "name" "rbac-policy") | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.rbac.secretStore }}
    kind: {{ .Values.externalSecrets.rbac.secretStoreKind }}

  target:
    name: argocd-rbac-cm
    creationPolicy: Merge
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: argocd-rbac-cm
          app.kubernetes.io/part-of: argocd
          app.kubernetes.io/component: server
      engineVersion: v2
      mergePolicy: Merge
      data:
        policy.csv: |
          {{`{{- range (split "," (index . "admin.emails")) }}`}}
          g, {{`{{ . }}`}}, role:admin
          {{`{{- end }}`}}

  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.rbac.secretKey }}
{{- end }}
