apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-sql-restore-sa
  namespace: ojeomneo
  annotations:
    iam.gke.io/gcp-service-account: cloud-sql-restore-sa@infra-480802.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-sql-restore-role
  namespace: ojeomneo
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-sql-restore-binding
  namespace: ojeomneo
subjects:
  - kind: ServiceAccount
    name: cloud-sql-restore-sa
    namespace: ojeomneo
roleRef:
  kind: Role
  name: cloud-sql-restore-role
  apiGroup: rbac.authorization.k8s.io
