{{- if or .Values.configMap.enabled .Values.configMap.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin.fullname" . }}
  labels:
    {{- include "admin.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
