apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-headless
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- if or (include "redis.annotations" .) .Values.service.headless.annotations }}
  annotations:
    {{- with (include "redis.annotations" .) }}
    {{- include "cloudpirates.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- with .Values.service.headless.annotations }}
    {{- include "cloudpirates.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
    {{- range .Values.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .name }}
      name: {{ .name }}
    {{- end }}
    {{- if and .Values.sentinel.enabled (eq .Values.architecture "replication") }}
    - port: {{ .Values.sentinel.port }}
      targetPort: sentinel
      protocol: TCP
      name: sentinel
    {{- end }}
    {{- if eq .Values.architecture "cluster" }}
    - port: {{ .Values.service.clusterPort }}
      targetPort: cluster
      protocol: TCP
      name: cluster
    {{- end }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}