{{- if or .Values.serviceAccount.create (and .Values.sentinel.enabled .Values.sentinel.masterService.enabled) }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "redis.serviceAccountName" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- $annotations := merge .Values.serviceAccount.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
