apiVersion: v2
name: hotsao
description: Hotsao (핫사오) - Go Scraper + Redis + RabbitMQ (Server/Web 추후 구현)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- condition: go-scraper.enabled
  name: go-scraper
  repository: file://./charts/go-scraper
  version: 1.0.0
- condition: server.enabled
  name: server
  repository: file://./charts/server
  version: 2.1.1
- condition: web.enabled
  name: web
  repository: file://./charts/web
  version: 1.0.0
- condition: redis.enabled
  name: redis
  repository: file://./charts/redis
  version: 0.18.0
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: file://./charts/rabbitmq
  version: 15.5.3
