apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "woohalabs-app-ads.fullname" . }}
  labels:
    {{- include "woohalabs-app-ads.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "woohalabs-app-ads.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "woohalabs-app-ads.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        volumeMounts:
        - name: app-ads
          mountPath: /usr/share/nginx/html/app-ads.txt
          subPath: app-ads.txt
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /app-ads.txt
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /app-ads.txt
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: app-ads
        configMap:
          name: {{ include "woohalabs-app-ads.fullname" . }}
          items:
          - key: app-ads.txt
            path: app-ads.txt
      - name: nginx-config
        configMap:
          name: {{ include "woohalabs-app-ads.fullname" . }}
          items:
          - key: default.conf
            path: default.conf
