apiVersion: v2
appVersion: v0.0.16
description: A Helm chart for deploying SigNoz Opentelemetry Gateway
home: https://signoz.io/
icon: https://signoz.io/img/SigNozLogo-orange.svg
maintainers:
- email: devops@signoz.io
  name: SigNoz
  url: https://signoz.io
name: signoz-otel-gateway
type: application
version: 0.0.4
