apiVersion: v2
appVersion: 2.1.3
dependencies:
- condition: scrape.enabled
  name: scrape
  repository: file://./charts/scrape
  version: 2.1.3
- condition: server.enabled
  name: server
  repository: file://./charts/server
  version: 2.1.1
- condition: admin.enabled
  name: admin
  repository: file://./charts/admin
  version: 1.0.0
# Database subchart disabled - using Cloud SQL instead
# - condition: database.enabled
#   name: database
#   repository: file://./charts/database
#   version: 2.31.3
description: A Helm chart for Kubernetes
name: reviewmaps
type: application
version: 2.1.3
