#########################################################################
# scrape 설정
#########################################################################
scrape:
  enabled: true
  # Default values for backend.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: ggorockee/scrape-with-selenium
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "20251114-36c39d7"

  # This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []
  # This is to override the chart name.
  nameOverride: ""
  fullnameOverride: ""

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels:
    job: scrape
    service: scrape

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: ClusterIP
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    port: 8000
    portName: "fastapi"

  # This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe: {}
    # httpGet:
    #   path: /
    #   port: http

  readinessProbe: {}
    # httpGet:
    #   path: /
    #   port: http

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}

  tolerations: []

  affinity: {}

  configMap:
    enabled: true
    # name을 지정하지 않으면 차트 이름 기반으로 자동 생성됩니다.
    name: ""
    data:
      BASE_URL: "https://inflexer.net"
      HEADLESS: "true"
      # 배치 스케줄 동작 (코드의 Settings와 매핑)
      BATCH_MODE: "once"                    # once|daily|interval (runner.mode=once면 여기 값 무시해도 됨)
      BATCH_TIME: "01:00"                    # daily 모드일 때
      BATCH_INTERVAL_SECONDS: "300"          # interval 모드일 때
      TIMEZONE: "Asia/Seoul"
      RUN_AT_START: "false"                  # 시작 직후 1회 실행 여부
      TABLE_NAME: "campaign"
      ENRICH_SCOPE: "region" # region | all
      WAIT_TIMEOUT: "300"

  secret:
    enabled: true
    # 클러스터에 미리 생성되어 있어야 하는 Secret 이름들의 목록
    names:
      - "reviewmaps-db-credentials"
      - "naver-api-creds"
  runner:
    enabled: true
    mode: "once"                             # once | daily | interval
    # CronJob로 돌릴 때
    scrapers:
      - name: mymilky
        schedule: "0 1 * * *"                    # 매일 01:00
        timeZone: "Asia/Seoul"                   # 클러스터가 지원하면 적용됨
        concurrencyPolicy: "Forbid"
        startingDeadlineSeconds: 900
        successfulJobsHistoryLimit: 0
        failedJobsHistoryLimit: 1
        backoffLimit: 2
        ttlSecondsAfterFinished: 0
        keywords:
          - "서울"
          - "부산"
          - "대구"
          - "인천"
          - "광주"
          - "대전"
          - "울산"
          - "세종"
          - "강원"
          - "경기"
          - "경남"
          - "경북"
          - "전남"
          - "전북"
          - "충남"
          - "충북"
          - "제주"
        parallel:
            # 병렬 처리를 사용할지 여부
          enabled: true
          maxParallelism: 1



      - name: inflexer
        schedule: "0 3 * * *"                    # 매일 01:00
        timeZone: "Asia/Seoul"                   # 클러스터가 지원하면 적용됨
        concurrencyPolicy: "Forbid"
        startingDeadlineSeconds: 900
        successfulJobsHistoryLimit: 0
        failedJobsHistoryLimit: 1
        backoffLimit: 2
        ttlSecondsAfterFinished: 0
        keywords:
          - "인천 중구"
          - "서울 강남"
          - "서울 강동"
          - "서울 강북"
          - "서울 강서"
          - "서울 관악"
          - "서울 광진"
          - "서울 구로"
          - "서울 금천"
          - "서울 노원"
          - "서울 도봉"
          - "서울 동대문"
          - "서울 동작"
          - "서울 마포"
          - "서울 서대문"
          - "서울 서초"
          - "서울 성동"
          - "서울 성북"
          - "서울 송파"
          - "서울 양천"
          - "서울 영등포"
          - "서울 용산"
          - "서울 은평"
          - "서울 종로"
          - "서울 중구"
          - "서울 중랑"
          - "경기 가평"
          - "경기 고양"
          - "경기 과천"
          - "경기 광명"
          - "경기 광주"
          - "경기 구리"
          - "경기 군포"
          - "경기 김포"
          - "경기 남양주"
          - "경기 동두천"
          - "경기 부천"
          - "경기 성남"
          - "경기 수원"
          - "경기 시흥"
          - "경기 안산"
          - "경기 안성"
          - "경기 안양"
          - "경기 양주"
          - "경기 양평"
          - "경기 여주"
          - "경기 연천"
          - "경기 오산"
          - "경기 용인"
          - "경기 의왕"
          - "경기 의정부"
          - "경기 이천"
          - "경기 파주"
          - "경기 평택"
          - "경기 포천"
          - "경기 하남"
          - "경기 화성"
          - "인천 강화"
          - "인천 계양"
          - "인천 미추홀"
          - "인천 남동"
          - "인천 동구"
          - "인천 부평"
          - "인천 서구"
          - "인천 연수"
          - "인천 옹진"
          - "강원"
          - "충북"
          - "충남"
          - "전남"
          - "전북"
          - "울산"
          - "부산"
          - "제주"
          - "경북"
          - "경남"
          - "대구"
          - "광주"
          - "대전"
          - "세종"
        parallel:
            # 병렬 처리를 사용할지 여부
          enabled: true
          maxParallelism: 1

    # Deployment(내부 스케줄러)로 돌릴 때
    deployment:
      enabled: false                         # 내부 스케줄러(상주형) 사용할지
      replicas: 1

  cleanup:
    enabled: true
    schedule: "0 6 * * *"                    # 매일 새벽 6시
    timeZone: "Asia/Seoul"
    concurrencyPolicy: "Forbid"
    startingDeadlineSeconds: 1800           # 30분
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 5
    backoffLimit: 3
    ttlSecondsAfterFinished: 7200            # 2시간 후 정리
    # 정리할 테이블 및 조건 설정
    tables:
      - name: "campaign"                     # 테이블명
        condition: "apply_deadline < CURRENT_DATE"  # 삭제 조건
        batchSize: 1000                      # 배치 크기 (한 번에 삭제할 레코드 수)
      # - name: "reviews"                      # 다른 테이블도 추가 가능
      #   condition: "created_at < CURRENT_DATE - INTERVAL '30 days'"
      #   batchSize: 500  



#########################################################################

#########################################################################

server:
  enabled: true
  # Default values for backend.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1
  revisionHistoryLimit: 1

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: ggorockee/reviewmaps-server
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "20251205-a2362b8"

  # This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []
  # This is to override the chart name.
  nameOverride: ""
  fullnameOverride: ""

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels:
    app: "reviewmaps-server"
    job: "reviewmaps-server"

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: ClusterIP
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    port: 3000
    portName: "http"

  # This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi


  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /healthz
      port: http
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  startupProbe:
    httpGet:
      path: /healthz
      port: http
      scheme: HTTP
    initialDelaySeconds: 0
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 12

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}

  tolerations: []

  affinity: {}

  configMap:
    enabled: true
    # name을 지정하지 않으면 차트 이름 기반으로 자동 생성됩니다.
    name: ""
    data:
      SERVER_ENV: "production"
      SERVER_PORT: "3000"
      PROMETHEUS_MULTIPROC_DIR: "/tmp/metrics"
      DEBUG: "False"  # 프로덕션
      ALLOWED_HOSTS: "*"
      JWT_ALGORITHM: "HS256"
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "60"
      JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
      # POSTGRES_* 환경변수는 reviewmaps-db-credentials secret에서 주입됨
      POSTGRES_SSLMODE: "disable"
      # OpenTelemetry/SigNoz 설정
      SIGNOZ_ENDPOINT: "http://signoz-otel-collector.monitoring.svc.cluster.local:4318"
      # BASE_URL: "https://inflexer.net"
      # HEADLESS: "true"
      # # 배치 스케줄 동작 (코드의 Settings와 매핑)
      # BATCH_MODE: "daily"                    # once|daily|interval (runner.mode=once면 여기 값 무시해도 됨)
      # BATCH_TIME: "01:00"                    # daily 모드일 때
      # BATCH_INTERVAL_SECONDS: "300"          # interval 모드일 때
      # TIMEZONE: "Asia/Seoul"
      # RUN_AT_START: "false"                  # 시작 직후 1회 실행 여부
      # TABLE_CAMPAIGN: "campaign"
      # LOG_LEVEL: "info"
      # APP_ENV: "production"

  secret:
    enabled: true
    # 클러스터에 미리 생성되어 있어야 하는 Secret 이름들의 목록
    names:
      - reviewmaps-db-credentials
      - reviewmaps-api-credentials

  # DB Migration Job 설정
  migration:
    enabled: false
    # Job 실행 명령어 (기본값: python manage.py migrate)
    command: ["python", "manage.py", "migrate"]
    # 추가 인수 (optional)
    args: []
    # Job backoff limit
    backoffLimit: 3
    # Job TTL after finished (초 단위, 기본: 1시간)
    ttlSecondsAfterFinished: 3600
    # Job restart policy
    restartPolicy: OnFailure

  # Prometheus Metrics 설정
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
    # Gauge 메트릭 수집 CronJob 설정 (APScheduler로 대체됨)
    collector:
      enabled: false  # APScheduler가 Django 프로세스 내에서 수집
      schedule: "*/5 * * * *"
      timeZone: "Asia/Seoul"
      concurrencyPolicy: "Forbid"
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 3
      startingDeadlineSeconds: 300
      ttlSecondsAfterFinished: 3600
      backoffLimit: 2
      restartPolicy: "OnFailure"



#########################################################################

#########################################################################
admin:
  enabled: true
  # Django Admin for ReviewMaps
  # This is a YAML-formatted file.

  replicaCount: 1
  revisionHistoryLimit: 1

  image:
    repository: ggorockee/reviewmaps-admin
    pullPolicy: IfNotPresent
    tag: "20251205-9d78296"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

  podAnnotations: {}
  podLabels:
    app: "reviewmaps-admin"
    job: "reviewmaps-admin"

  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 8000
    portName: "django"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  livenessProbe:
    httpGet:
      path: /admin/
      port: django
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /admin/
      port: django
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  startupProbe:
    httpGet:
      path: /admin/
      port: django
      scheme: HTTP
    initialDelaySeconds: 0
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 12

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80

  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

  configMap:
    enabled: true
    name: ""
    data:
      DEBUG: "False"
      ALLOWED_HOSTS: "admin.review-maps.com,localhost,127.0.0.1"
      # POSTGRES_* 환경변수는 reviewmaps-db-credentials secret에서 주입됨
      POSTGRES_SSLMODE: "disable"

  secret:
    enabled: true
    names:
      - reviewmaps-db-credentials
      - reviewmaps-api-credentials

  migration:
    enabled: true
    command: ["python", "manage.py", "migrate"]
    args: []
    backoffLimit: 3
    ttlSecondsAfterFinished: 3600
    restartPolicy: OnFailure

  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      interval: 30s
      scrapeTimeout: 10s
    collector:
      enabled: false

#########################################################################

#########################################################################
web:
  enabled: false

#########################################################################

#########################################################################

database:
  enabled: true
  global:
    postgresql:
      auth:
        username: reviewmaps
        database: reviewmaps
        existingSecret: reviewmaps-db-credentials

  primary:
    persistence:
      size: 20Gi
      volumeName: "data"
    # 리소스 설정 추가 (OOM Kill 방지)
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    # Probe 타임아웃 증가 (느린 응답 대비)
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 15
      timeoutSeconds: 10
      failureThreshold: 6
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 6
