env: prod
revision: main
chartName: kube-prometheus-stack
appName: kube-prometheus-stack
repoURL: https://github.com/ggorockee/infra
namespace: monitoring
# Custom values 파일 (values.yaml 외 추가로 적용)
additionalValueFile: values-override.yaml
