apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: reviewmaps-db-credentials
  namespace: reviewmaps
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: reviewmaps-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_HOST
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_PORT
    - secretKey: POSTGRES_USER
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: prod-reviewmaps-db-credentials
        property: POSTGRES_DB
