{{- if .Values.ssl.enabled }}
{{- if .Values.ssl.clusterIssuer.enabled }}
---
# Let's Encrypt Production ClusterIssuer
{{- if .Values.ssl.clusterIssuer.production.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ssl.clusterIssuer.production.name }}
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  acme:
    server: {{ .Values.ssl.clusterIssuer.production.server }}
    email: {{ .Values.ssl.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.ssl.clusterIssuer.production.privateKeySecretRef }}
    solvers:
    - dns01:
        cloudDNS:
          project: {{ .Values.ssl.clusterIssuer.gcpProjectId }}
          serviceAccountSecretRef:
            name: {{ .Values.ssl.clusterIssuer.dnsSecretName }}
            key: {{ .Values.ssl.clusterIssuer.dnsSecretKey }}
{{- end }}
---
# Let's Encrypt Staging ClusterIssuer
{{- if .Values.ssl.clusterIssuer.staging.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ssl.clusterIssuer.staging.name }}
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  acme:
    server: {{ .Values.ssl.clusterIssuer.staging.server }}
    email: {{ .Values.ssl.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.ssl.clusterIssuer.staging.privateKeySecretRef }}
    solvers:
    - dns01:
        cloudDNS:
          project: {{ .Values.ssl.clusterIssuer.gcpProjectId }}
          serviceAccountSecretRef:
            name: {{ .Values.ssl.clusterIssuer.dnsSecretName }}
            key: {{ .Values.ssl.clusterIssuer.dnsSecretKey }}
{{- end }}
{{- end }}
{{- end }}
