{{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- with .Values.storageClass.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.storageClass.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    {{- with .Values.storageClass.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  {{- with .Values.storageClass.parameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
{{- end }}

{{- range .Values.additionalStorageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  labels:
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
provisioner: {{ .provisioner }}
parameters:
  {{- with .parameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
volumeBindingMode: {{ .volumeBindingMode }}
allowVolumeExpansion: {{ .allowVolumeExpansion }}
reclaimPolicy: {{ .reclaimPolicy }}
{{- end }}
