apiVersion: v2
appVersion: 1.0.0
dependencies:
- condition: server.enabled
  name: server
  repository: file://./charts/server
  version: 1.0.0
- condition: database.enabled
  name: database
  repository: file://./charts/database
  version: 1.0.0
description: Ojeomneo (오점너) - Go Fiber v2 API Server with PostgreSQL
name: ojeomneo
type: application
version: 1.0.0
