{{- if .Values.ssl.enabled }}
{{- if .Values.ssl.externalSecret.enabled }}
---
# ExternalSecret for Cloud DNS Service Account credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ssl.externalSecret.name }}
  namespace: {{ .Values.ssl.externalSecret.namespace }}
spec:
  refreshInterval: {{ .Values.ssl.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.ssl.externalSecret.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.ssl.externalSecret.name }}
    creationPolicy: Owner
  data:
  - secretKey: {{ .Values.ssl.externalSecret.secretKey }}
    remoteRef:
      key: {{ .Values.ssl.externalSecret.gcpSecretName }}
{{- end }}
{{- end }}
